# Generated by Django 5.0 on 2023-12-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perssonnage',
            name='name',
            field=models.CharField(default='pacman', max_length=64),
        ),
        migrations.AddField(
            model_name='perssonnage',
            name='skin',
            field=models.CharField(default='pacman', max_length=64),
        ),
    ]
