# Generated by Django 5.0 on 2023-12-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe_core', '0003_rename_perssonnage_personnage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
